apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
    env: production
spec:
  containers:
  - name: my-nginx-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

