apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
        env: production
    spec:
      containers:
      - name: my-nginx-pod
        image: nginx  
        
