apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels: 
      app: myapp
spec:
  replicas: 6
  selector:
      matchLabels:
        app: myapp
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
        env: produc
    spec:
      containers:
      - name: nginx-container
        image: nginx  
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  





